### ISSUE TITLE
Find CSV containing coordinates of US counties

### ISSUE THREAD

**Issue by Forte42** [Forte42/Realestate_of_Mind#11]
I have the zillow API and data. The last thing I need would be a dataframe containing coordinates of US counties.

- Review kaggle.com 
- Zillow may have the data as well
- Realtor.com has updated data for 12 counties 
- Wikipedia - 3000+ locations

**Comment by kmpotter2** [comment]
https://en.wikipedia.org/wiki/User:Michael_J/County_table

**Comment by matthewhoo** [comment]
https://docs.gaslamp.media/download-zip-code-latitude-longitude-city-state-county-csv/

**Comment by smruthid** [comment]
https://www.census.gov/data/developers/data-sets/Geocoding-services.html

**Comment by smruthid** [comment]
https://www.openstreetmap.org/#map=4/38.01/-95.84
