### ISSUE TITLE
Host Jupyter Notebook in the cloud (formerly `make webpage`)

### ISSUE THREAD

**Issue by Forte42** [Forte42/Realestate_of_Mind#9]
It would be ideal to host the Jupyter notebook in the cloud so that users can browse through the notebook and execute the calculations online without running it locally.   

Some options incude: 
- Convert Jupyter notebook using Voila
- Convert Jupyter notebook to python and host with Streamlit
- Convert Jupyter notebook to HTML and host with AWS

**Comment by quinnwong31** [comment]
We moved functionality into Python modules and created a StreamLit application instead.
